### PR TITLE
Adding correct rfcp for local stageout jobs

### PR DESCRIPTION
**Pull request by mmusich**

### CODE REVIEW

**Comment by emiglior** [comment]
@mmusich why rfcp and not just cp?

**Comment by mmusich** [comment]
@emiglior I copied the syntax from some other scripts hanging around in CMSSW that seem to work. If you feel confident cp will work fine from lxbatch I can do the change

**Comment by emiglior** [comment]
@mmusich let's wait the test Bilal is running

**Comment by mmusich** [comment]
let me introduce @mkiani as well then

**Comment by mmusich** [comment]
@emiglior @mkiani any updates on this?

**Comment by mkiani** [comment]
@emiglior  I checked there is a root tuple in my local directory results/../../... created on 1st April when we submitted the jobs but when I checked the PixelLocalRecoBuildAndRun.py there is still cmsStage instead of 'cp' which I remember you changed. So doing it again to confirm....

**Comment by emiglior** [comment]
@mkiani @mmusich 
If I am not mistaken, we just modified (and resubmitted) the .lsf. We did not recreate the job using PixelLocalRecoBuildAndRun.py

**Comment by emiglior** [comment]
@mmusich @mkiani
Tested (using a dummy script) that cp copies from lxbatch to cern afs

**Comment by mmusich** [comment]
@emiglior please acknowledge changes as in [92849b1](https://github.com/mmusich/usercode-SLHCSimulation/commit/92849b1661263c3ca05d2975ee0754987f006360)

**Pull request merged**
